name: clubedematematica
description: Possibilita a criação de clubes de matemática, onde o administrador pode encaminhar questões das provas da OBMEP aos membros do clube.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  firebase_core: ^0.5.0 #Recursos básicos
  cloud_firestore: ^0.14.0+2 #Banco de dados
  firebase_storage: ^4.0.0 #Armazenamento de arquivos
  firebase_auth: ^0.18.0+1 #Autenticação
  google_sign_in: ^4.5.9 #Login com uma conta Google
  catex: ^0.0.1+6 #^0.0.1+7
  progressive_image: ^1.0.1 #Um widget de vibração que carrega progressivamente imagens grandes usando espaços reservados para imagens de baixa qualidade.
  path: ^1.8.0-nullsafety.1 #Fornece operações comuns para manipulação de caminhos: junção, divisão, normalização, etc.
  path_provider: ^1.6.27 #Um plugin Flutter para encontrar locais comumente usados ​​no sistema de arquivos. Suporta iOS, Android, Linux e MacOS. Nem todos os métodos são suportados em todas as plataformas.
  dio: ^3.0.10 #Um cliente Http poderoso para Dart, que suporta interceptores, configuração global, FormData, cancelamento de solicitação, download de arquivo, tempo limite etc.
  transparent_image: ^1.0.0 #Uma imagem transparente simples. Representado como um Uint8List. Este pacote exporta uma constante: kTransparentImage.
  image_size_getter: ^0.2.1 #Usado para obter a largura e a altura dos arquivos de imágem.
  diacritic: ^0.1.1 #Remove acentos comuns e sinais diacríticos de uma string, substituindo-os por um caractere equivalente.
  image_picker: ^0.6.7+22 #Seletor de imagens.
  flutter_modular: ^2.0.1 #provedor de dependencias (widgets acessiveis em toda a sua sub-arvore) e rotas
  #dependencias para usar o mobx como gerenciador de estado
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #dependencias para usar o gerador de codigo do mobx
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.13

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - lib/app/modules/login/assets/google_logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
