import 'package:clubedematematica/app/modules/quiz/shared/utils/rotas_quiz.dart';

const ROTA_MODULO_FILTROS = "/filtro";
const ROTA_MODULO_FILTROS_PATH = ROTA_PAGINA_QUIZ + ROTA_MODULO_FILTROS;

///ROTA_MODULO_FILTROS + "/tipos"
const ROTA_PAGINA_FILTROS_TIPOS = "/tipos";
const ROTA_PAGINA_FILTROS_TIPOS_PATH = ROTA_MODULO_FILTROS_PATH + ROTA_PAGINA_FILTROS_TIPOS;

///ROTA_MODULO_FILTROS + "/opcoes"
const ROTA_PAGINA_FILTROS_OPCOES = "/opcoes";
const ROTA_PAGINA_FILTROS_OPCOES_PATH = ROTA_MODULO_FILTROS_PATH + ROTA_PAGINA_FILTROS_OPCOES;