// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlQYxuraoy2pXxVrS_O3_tDsfi42kPajs',
    appId: '1:760657363926:web:6fb3d53a38b6cfe3851a77',
    messagingSenderId: '760657363926',
    projectId: 'clube-de-matematica',
    authDomain: 'clube-de-matematica.firebaseapp.com',
    databaseURL: 'https://clube-de-matematica.firebaseio.com',
    storageBucket: 'clube-de-matematica.appspot.com',
    measurementId: 'G-HWMVLK2YF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZtdMrZ7NsJuS4cKXf8BCZhmSXiVC8hpA',
    appId: '1:760657363926:android:0b3c6e7cd4c4f997851a77',
    messagingSenderId: '760657363926',
    projectId: 'clube-de-matematica',
    databaseURL: 'https://clube-de-matematica.firebaseio.com',
    storageBucket: 'clube-de-matematica.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUtMjxiyQ6-YH4bK1szUhpXhpTkime3_E',
    appId: '1:760657363926:ios:688cfe645ae1e9d3851a77',
    messagingSenderId: '760657363926',
    projectId: 'clube-de-matematica',
    databaseURL: 'https://clube-de-matematica.firebaseio.com',
    storageBucket: 'clube-de-matematica.appspot.com',
    androidClientId: '760657363926-1gt52lcdk9n2jp4heo7aj2evs9srldgp.apps.googleusercontent.com',
    iosClientId: '760657363926-t0b9rt7cemhplk6b3geasr8m31klbou4.apps.googleusercontent.com',
    iosBundleId: 'com.sslourenco.clubedematematica',
  );
}
